### ISSUE TITLE
Date will not update when I export attendance

### ISSUE THREAD

**Issue by SBoone20** [tytot/attendance-for-google-meet#4]
Whenever I attempt to export the attendance in to the excel file it continuously pulls the attendance from the first day I used the extension on 09/29.  It will not update the attendance or date whenever I attempt to export it now.

**Comment by tytot** [comment]
Could you try the following steps?

1. Click on the extension icon at the top right of the browser
2. Click "SHOW ADVANCED"
3. Click "CLEAR STORAGE"
4. Click "YES"

Does the error persist?

**Comment by jblondon** [comment]
I have been having this issue for the past two days where I receive an error message that "An error occurred while updating the spreadsheet. Please try again later." It was not working for one of the classes I created yesterday but the other two worked fine. This morning, one of them worked fine and the second one would not work. I tried the steps listed above and I am still receiving the same error message.

**Comment by tytot** [comment]
> I have been having this issue for the past two days where I receive an error message that "An error occurred while updating the spreadsheet. Please try again later." It was not working for one of the classes I created yesterday but the other two worked fine. This morning, one of them worked fine and the second one would not work. I tried the steps listed above and I am still receiving the same error message.

This seems to be a problem with your spreadsheet. Try following the steps above, but instead of clicking "CLEAR STORAGE", click "UNLINK SPREADSHEET". If you continue to experience this issue, please open a new issue.
