### ISSUE TITLE
Data does not export

### ISSUE THREAD

**Issue by aoelfke** [tytot/attendance-for-google-meet#5]
At the end of a class, when I hit the export button, the spreadsheet does not update.

**Comment by tytot** [comment]
Hi, it looks like your previous issue might be the same issue. Do you get an error message when hitting export, or does it say that it exported successfully?

**Comment by aoelfke** [comment]
No, it says there is an error.  If it happens again today, I will make note of the exact language.

Alicia Feddor Oelfke
________________________________
Input  Learner  Connectedness  Arranger  Intellection
________________________________
Science Teacher and Team Leader
Glenwood Middle School
Visit my webpage!<https://sites.google.com/a/hcpss.org/mrs-oelfke/>
________________________________

**Comment by aoelfke** [comment]
"An error occurred while accessing the spreadsheet.  Please try again later."

Alicia Feddor Oelfke
________________________________
Input  Learner  Connectedness  Arranger  Intellection
________________________________
Science Teacher and Team Leader
Glenwood Middle School
Visit my webpage!<https://sites.google.com/a/hcpss.org/mrs-oelfke/>
________________________________

**Comment by tytot** [comment]
If you still have this issue, please try clicking on the extension icon in Google Chrome, clicking "SHOW ADVANCED", and then clicking "UNLINK SPREADSHEET". This should reset the connection to your spreadsheet and resolve any errors; however you will have to use the new spreadsheet.
