### ISSUE TITLE
Unable to select a class

### ISSUE THREAD

**Issue by krhof** [tytot/attendance-for-google-meet#6]
When a choose my class and click on select, the class list does not appear and no data is collected.  I have deleted the extension and reinstalled; however, that did not solve the problem.  A fellow teacher is have the same issue.

![Google Attendance](https://user-images.githubusercontent.com/74431410/99118760-b293a800-25bd-11eb-95d9-b4138b1857c7.JPG)

**Comment by CosmicCoffee** [comment]
This is an issue across the board

**Comment by tytot** [comment]
Sorry for the inconvenience; it was a problem with Google Meet's internal code. We have fixed the issue and published an update that should be out by tomorrow. Thanks!
