### ISSUE TITLE
export process freezes and never completes

### ISSUE THREAD

**Issue by iupbvrdm** [tytot/attendance-for-google-meet#7]
This prevents the data from exporting to the spreadsheet.  This is a new problem that has only begun happening this week.

**Comment by krhof** [comment]
I am having the same problem.  Export starts but freezes before finishing.  Not data is collected.

**Comment by aalkz** [comment]
Same problem here.

![image](https://user-images.githubusercontent.com/6750582/100184253-b4efdf00-2ea6-11eb-874d-289c4f4c4be9.png)

Also, spreadsheet is created but it's blank

**Comment by tytot** [comment]
Thank you all for the issue report. This is a strange problem because exporting works on my computer, but not on anyone else's. However, we think that we have a solution that should resolve the problem by next week.
