### ISSUE TITLE
The user did not approve access 

### ISSUE THREAD

**Issue by TechnicalGurujiC** [tytot/attendance-for-google-meet#9]
Work perfectly fine on the google meet tab but when I press Export Button, it shows **The user did not approve access**

_**PLEASE HELP
![Screenshot (18)](https://user-images.githubusercontent.com/77566594/104835052-ea72e080-58c9-11eb-9f5a-202f7533a2eb.png)
**_

**Comment by neyoungaba** [comment]
I'm having this problem too. Any solutions yet?

**Comment by tytot** [comment]
Sorry, I have been unable to reproduce this issue. Could you try logging out of your Google account and trying to export again?

If that doesn't work, please try going to https://myaccount.google.com/, clicking on Security, clicking on Manage third-party access, and removing access from Attendance for Google Meet. Then try exporting again.

**Comment by MidnightQuery** [comment]
i have the same problem but i used edge i am not sure if that is the cause though.
i was never asked for permission by the extensions. maybe it is caused by edge after all?
edit: confirmed it worked on chrome, any chances to fix it for edge?

**Comment by tytot** [comment]
> i have the same problem but i used edge i am not sure if that is the cause though.
> i was never asked for permission by the extensions. maybe it is caused by edge after all?
> edit: confirmed it worked on chrome, any chances to fix it for edge?

We do not currently support Edge but we are considering doing so in the future. Thanks

**Comment by tytot** [comment]
Closed due to duplicate issue. Please refer to #8.
